# Based on https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/deploy-github-actions?tabs=CLI and https://github.com/Rightpoint/cloud-platform-exploration-azure-container-app/blob/main/.github/workflows/infrastructure.yml

name: Deploy infrastructure

on:
  workflow_dispatch:
  push:
    branches:
     - main
    paths:
     - .github/workflows/infrastructure.yml
     - infrastructure/**

# Using OpenID Connect - https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Cwindows#use-the-azure-login-action-with-openid-connect
# If you get a "No subscriptions found for ..." error, you forgot to grant the service pricipal any permissions
permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: OIDC Login to Azure Public Cloud
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ vars.AZURE_RESOURCE_GROUP }}
          template: infrastructure/main.bicep
          failOnStdErr: false
          scope: 'resourcegroup'
          parameters: location=${{ vars.AZURE_LOCATION }} openAiLocation=${{ vars.AZURE_OPEN_AI_LOCATION }}
